# PlatformIO pre-build script: bake factory defaults from hardware_defaults.ini
# into the firmware.
#
# Reads the [machine] section of hardware_defaults.ini (project root) and
# generates include/generated/hardware_defaults.h with C literals. The
# firmware applies these on first boot when no machine has been configured yet
# (MachineConfigManager::applyBuildDefaults) and pre-fills the "Add Machine"
# dialog with them.
#
# Behavior:
#   - Missing file, missing section, or empty ssid/url -> defaults disabled
#     (FLUIDTOUCH_BUILD_DEFAULTS_VALID 0); the firmware behaves as before.
#   - Values longer than the MachineConfig field sizes are truncated (warned).
#   - The header is only rewritten when its content changes, so unchanged
#     values do not trigger full rebuilds.

Import("env")

import configparser
import os

PROJECT_DIR = env["PROJECT_DIR"]
INI_PATH = os.path.join(PROJECT_DIR, "hardware_defaults.ini")
OUT_DIR = os.path.join(PROJECT_DIR, "include", "generated")
OUT_PATH = os.path.join(OUT_DIR, "hardware_defaults.h")

# Field size limits - must match struct MachineConfig (include/ui/machine_config.h)
LIMITS = {"name": 31, "ssid": 32, "password": 63, "url": 127}
DEFAULT_PORT = 81
FALLBACK_NAME = "My CNC"  # used when defaults are enabled but name is empty


def log(msg):
    print("generate_defaults: " + msg)


def read_ini():
    """Return raw string values from hardware_defaults.ini ("" when absent)."""
    values = {"name": "", "ssid": "", "password": "", "url": "", "port": ""}
    if not os.path.isfile(INI_PATH):
        log("hardware_defaults.ini not found - factory defaults disabled")
        return values
    parser = configparser.ConfigParser(
        interpolation=None, inline_comment_prefixes=(";", "#")
    )
    try:
        parser.read(INI_PATH, encoding="utf-8")
    except (configparser.Error, UnicodeDecodeError) as e:
        log("WARNING could not parse hardware_defaults.ini (%s) - defaults disabled" % e)
        return values
    if not parser.has_section("machine"):
        log("no [machine] section in hardware_defaults.ini - factory defaults disabled")
        return values
    section = parser["machine"]
    for key in values:
        values[key] = section.get(key, "").strip()
    return values


def parse_port(raw):
    if not raw:
        return DEFAULT_PORT
    try:
        port = int(raw)
        if 1 <= port <= 65535:
            return port
    except ValueError:
        pass
    log("WARNING invalid port %r (use 1-65535), using %d" % (raw, DEFAULT_PORT))
    return DEFAULT_PORT


def validate(values):
    for key, limit in LIMITS.items():
        if len(values[key]) > limit:
            log("WARNING %s is %d chars, truncating to %d (struct MachineConfig limit)"
                % (key, len(values[key]), limit))
            values[key] = values[key][:limit]


def c_literal(text):
    """Encode a Python string as a C string literal (UTF-8 passthrough)."""
    out = []
    for byte in text.encode("utf-8"):
        if byte == 0x5C:  # backslash
            out.append("\\\\")
        elif byte == 0x22:  # double quote
            out.append('\\"')
        elif 0x20 <= byte <= 0x7E:  # printable ASCII
            out.append(chr(byte))
        else:
            out.append("\\%03o" % byte)  # octal: exactly 3 digits, unambiguous
    return '"' + "".join(out) + '"'


def generate():
    values = read_ini()
    port = parse_port(values["port"])
    validate(values)

    # A usable default machine requires WiFi credentials and a FluidNC address
    # (only Wireless connections are supported by the UI today).
    enabled = bool(values["ssid"]) and bool(values["url"])
    if enabled and not values["name"]:
        values["name"] = FALLBACK_NAME

    defines = [
        ("FLUIDTOUCH_DEFAULT_MACHINE_NAME", c_literal(values["name"])),
        ("FLUIDTOUCH_DEFAULT_WIFI_SSID", c_literal(values["ssid"])),
        ("FLUIDTOUCH_DEFAULT_WIFI_PASSWORD", c_literal(values["password"])),
        ("FLUIDTOUCH_DEFAULT_FLUIDNC_URL", c_literal(values["url"])),
        ("FLUIDTOUCH_DEFAULT_WS_PORT", str(port)),
        ("FLUIDTOUCH_BUILD_DEFAULTS_VALID", "1" if enabled else "0"),
    ]

    lines = [
        "// AUTO-GENERATED by scripts/generate_defaults.py - DO NOT EDIT.",
        "// Source: hardware_defaults.ini. Edit that file and rebuild instead.",
        "#ifndef FLUIDTOUCH_HARDWARE_DEFAULTS_H",
        "#define FLUIDTOUCH_HARDWARE_DEFAULTS_H",
        "",
    ]
    if not enabled:
        lines.append("// Factory defaults disabled: hardware_defaults.ini needs both ssid and url.")
    for macro, value in defines:
        lines.append("#define %s %s" % (macro, value))
    lines += ["", "#endif // FLUIDTOUCH_HARDWARE_DEFAULTS_H", ""]

    content = "\n".join(lines)
    if os.path.isfile(OUT_PATH):
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            if f.read() == content:
                return  # unchanged: do not touch mtime (avoids needless rebuilds)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    rel = os.path.relpath(OUT_PATH, PROJECT_DIR)
    if enabled:
        log("factory defaults enabled (name=%r ssid=%r url=%r port=%d) -> %s"
            % (values["name"], values["ssid"], values["url"], port, rel))
    else:
        log("factory defaults disabled -> %s" % rel)


generate()
